const LOAD_ITEMS = 'ITEMS/LOAD';
const LOAD_MORE_ITEMS = 'ITEMS/LOAD_MORE';
const LOAD_ITEMS_SUCCESS = 'ITEMS/LOAD_SUCCESS';
const LOAD_ITEMS_ERROR = 'ITEMS/LOAD_ERROR';
const CANCEL_LOAD_ITEMS = 'ITEMS/CANCEL_LOAD';
const CHANGE_QUERY = 'QUERY/CHANGE';
const RESET_PAGING = 'PAGING/RESET';

export default {
	LOAD_ITEMS,
	LOAD_MORE_ITEMS,
	LOAD_ITEMS_SUCCESS,
	LOAD_ITEMS_ERROR,
	CANCEL_LOAD_ITEMS,
	CHANGE_QUERY,
	RESET_PAGING,
}